---
# Bring stack down
- hosts: lbs
  become: true
  tasks:
  - service: name=nginx state=stopped

- hosts: apps
  become: true
  tasks:
  - service: name=apache2 state=stopped

# Restart mysql
- hosts: dbs
  become: true
  tasks:
  - service: name=mysql state=restarted

# Bring stack up
- hosts: apps
  become: true
  tasks:
  - service: name=apache2 state=started

- hosts: lbs
  become: true
  tasks:
  - service: name=nginx state=started


